apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: platform-api
  namespace: phoenix-platform
---
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: platform-api
  namespace: phoenix-platform
spec:
  source:
    type: Binary
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: deploy/openshift/builds/platform-api/Containerfile
  output:
    to:
      kind: ImageStreamTag
      name: platform-api:latest
  triggers: []
---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: admin-portal
  namespace: phoenix-platform
---
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: admin-portal
  namespace: phoenix-platform
spec:
  source:
    type: Binary
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: deploy/openshift/builds/admin-portal/Containerfile
      buildArgs:
        - name: NEXT_PUBLIC_API_URL
          value: https://api.platform.ocp1.npd.co
  output:
    to:
      kind: ImageStreamTag
      name: admin-portal:latest
  triggers: []
