apiVersion: v2
name: phoenix-platform
description: EAOP Phoenix Platform umbrella chart
type: application
version: 0.1.0
appVersion: "0.1.0"

dependencies:
  - name: phoenix-infra
    version: 0.1.0
    repository: file://../phoenix-infra
    condition: phoenix-infra.enabled
  - name: platform-api
    version: 0.1.0
    repository: file://../platform-api
    condition: platform-api.enabled
  - name: admin-portal
    version: 0.1.0
    repository: file://../admin-portal
    condition: admin-portal.enabled
