FROM registry.access.redhat.com/ubi9/nodejs-20:latest AS builder

WORKDIR /opt/app
COPY apps/admin-portal/package*.json ./
RUN npm ci
COPY apps/admin-portal/ .
ARG NEXT_PUBLIC_API_URL=https://api.platform.ocp1.npd.co
ENV NEXT_PUBLIC_API_URL=$NEXT_PUBLIC_API_URL
RUN npm run build

FROM registry.access.redhat.com/ubi9/nodejs-20-minimal:latest
WORKDIR /opt/app
COPY --from=builder /opt/app/.next/standalone ./
COPY --from=builder /opt/app/.next/static ./.next/static
COPY --from=builder /opt/app/public ./public

ENV PORT=3000
EXPOSE 3000
CMD ["node", "server.js"]
